# Generated by Django 6.0.4 on 2026-04-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0003_opportunityresume"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="compensation_currency",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="expected_total_compensation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
