# Generated by Django 6.0.4 on 2026-04-25 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunities", "0002_opportunity_archived_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewCycle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_cycles",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InterviewStep",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("phone", "Phone screen"),
                            ("technical", "Technical"),
                            ("system_design", "System design"),
                            ("behavioral", "Behavioral"),
                            ("panel", "Panel"),
                            ("offer", "Offer"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No show"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "interviewer",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="interviews.interviewcycle",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cycle", "sequence"),
                        name="uniq_interview_step_sequence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="interview_step_sequence_gte_1",
                    ),
                ],
            },
        ),
    ]
