// Shared data-testid values. Duplicated verbatim in e2e/support/selectors.ts
// (kept in sync by hand; the e2e package is a standalone npm workspace).
export const TestIds = {
  LOGIN_USERNAME: "login-username",
  LOGIN_PASSWORD: "login-password",
  LOGIN_SUBMIT: "login-submit",
  SIGNED_IN_HEADER: "signed-in-header",
  SIGN_OUT_BUTTON: "sign-out-button",
  LANDING_CTA_PRIMARY: "landing-cta-primary",
  DASHBOARD_SIDEBAR: "dashboard-sidebar",
  DASHBOARD_HEADER: "dashboard-header",
  NAV_OPPORTUNITIES: "nav-opportunities",
  NAV_RESUMES: "nav-resumes",
  NAV_INTERVIEWS: "nav-interviews",
  NAV_SETTINGS: "nav-settings",
  STUB_PANEL: "stub-panel",
  OPPORTUNITIES_LIST: "opportunities-list",
  OPPORTUNITIES_EMPTY: "opportunities-empty",
  OPPORTUNITIES_ERROR: "opportunities-error",
  OPPORTUNITIES_LOADING: "opportunities-loading",
  OPPORTUNITIES_ROW: "opportunities-row",
  OPPORTUNITIES_NEW_BUTTON: "opportunities-new-button",
  OPPORTUNITY_CREATE_FORM: "opportunity-create-form",
  OPPORTUNITY_CREATE_TITLE: "opportunity-create-title",
  OPPORTUNITY_CREATE_COMPANY: "opportunity-create-company",
  OPPORTUNITY_CREATE_NOTES: "opportunity-create-notes",
  OPPORTUNITY_CREATE_SUBMIT: "opportunity-create-submit",
  OPPORTUNITY_CREATE_CANCEL: "opportunity-create-cancel",
  OPPORTUNITY_CREATE_ERROR: "opportunity-create-error",
  OPPORTUNITY_DETAIL_FORM: "opportunity-detail-form",
  OPPORTUNITY_DETAIL_TITLE: "opportunity-detail-title",
  OPPORTUNITY_DETAIL_COMPANY: "opportunity-detail-company",
  OPPORTUNITY_DETAIL_STAGE: "opportunity-detail-stage",
  OPPORTUNITY_DETAIL_NOTES: "opportunity-detail-notes",
  OPPORTUNITY_DETAIL_SAVE: "opportunity-detail-save",
  OPPORTUNITY_DETAIL_ARCHIVE: "opportunity-detail-archive",
  OPPORTUNITY_DETAIL_ARCHIVE_CONFIRM: "opportunity-detail-archive-confirm",
  OPPORTUNITY_DETAIL_ARCHIVE_CANCEL: "opportunity-detail-archive-cancel",
  OPPORTUNITY_DETAIL_ERROR: "opportunity-detail-error",
  OPPORTUNITY_DETAIL_NOT_FOUND: "opportunity-detail-not-found",
  OPPORTUNITY_DETAIL_BACK: "opportunity-detail-back",
  WORKSPACE_SWITCHER: "workspace-switcher",
  WORKSPACE_SWITCHER_LABEL: "workspace-switcher-label",
  WORKSPACE_SWITCHER_SELECT: "workspace-switcher-select",
} as const;

export type TestId = typeof TestIds[keyof typeof TestIds];
