# Generated by Django 6.0.4 on 2026-04-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseresume",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
