# Generated by Django 6.0.4 on 2026-04-25 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FxRate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("currency", models.CharField(max_length=8)),
                ("base_currency", models.CharField(max_length=8)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("date", models.DateField()),
                ("source", models.CharField(default="manual", max_length=32)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fx_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fx_rates",
                        to="tenancy.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "currency"),
                "indexes": [
                    models.Index(
                        fields=["workspace", "currency", "-date"],
                        name="fx_fxrate_workspa_5a0832_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "currency", "base_currency", "date"),
                        name="uniq_fx_rate_per_day",
                    )
                ],
            },
        ),
    ]
