# Generated by Django 6.0.4 on 2026-04-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TermsVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=32, unique=True)),
                ("body", models.TextField()),
                ("effective_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("-effective_at",),
            },
        ),
    ]
